# -*- coding: utf-8 -*-
"""2-maxsus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsmnIq-EeI0gzP-EL83x4O0BelxnHyWR
"""

from PIL import Image
import matplotlib.pyplot as plt


file_paths = ["japan.jpg", "rasm.png", "sher.jpeg"]

plt.figure(figsize=(15, 5))
for i, file_path in enumerate(file_paths):
    img = Image.open(file_path)

    img_gray = img.convert("L")

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title(f"Asl rasm {i + 1}")
    plt.axis("off")

    plt.subplot(2, 3, i + 4)
    plt.imshow(img_gray, cmap="gray")
    plt.title(f"Oq-qora rasm {i + 1}")
    plt.axis("off")

plt.tight_layout()
plt.show()